version: "3.4"

services:
  pokedex:
    image: pokedex
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: C:\progm\pokedex\src
        target: /app/src
